name = "mydnsproxy-dev"
main = "src/index.ts"
account_id = "b0d7b9f87b57470ef508f1a511093cae"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
routes = [
    { pattern = "adblock.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "family.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "freedom.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "paranoia.staging.mydns.network/*", zone_name = "mydns.network" }
]

# Observability
[observability]
enabled = true

# Static Assets
[assets]
directory = "./assets"
binding = "ASSETS"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "mydnsproxy-dev"

[[analytics_engine_datasets]]
binding = "ERROR_ANALYTICS"
dataset = "mydnsproxy-errors-dev"

# KV Namespace for resolver health scores
[[kv_namespaces]]
binding = "RESOLVER_HEALTH"
id = "5e16b351b2574a87929d8e32606b9539"

# Scheduled task for updating resolver health scores
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[env.prod]
name = "mydnsproxy-prod"
routes = [
    { pattern = "mydns.network/*", zone_name = "mydns.network" },
    { pattern = "www.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "adblock.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "family.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "freedom.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "paranoia.mydns.network/*", zone_name = "mydns.network" }
]

    [[env.prod.analytics_engine_datasets]]
    binding = "ANALYTICS"
    dataset = "mydnsproxy-prod"

    [[env.prod.analytics_engine_datasets]]
    binding = "ERROR_ANALYTICS"
    dataset = "mydnsproxy-errors-prod"

    [[env.prod.kv_namespaces]]
    binding = "RESOLVER_HEALTH"
    id = "950d3394e4464d11965ef46325fb6480"